language: php
sudo: false
php:
  - 7
  - 7.1
  - 7.2
cache:
  directories:
    - vendor
    - $HOME/.composer/cache
env:
  matrix:
    - DEPENDENCIES=""
    - DEPENDENCIES="--prefer-lowest --prefer-stable"
before_script:
  - composer self-update
  - composer update $DEPENDENCIES
  - if [ "$TRAVIS_PHP_VERSION" = "7.1" ] && [ "DEPENDENCIES" = "" ]; then composer require --dev phpstan/phpstan-shim friendsofphp/php-cs-fixer; fi
script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.clover;
  - php demo/run.php
  - if [ "$TRAVIS_PHP_VERSION" = "7.1" ] && [ "DEPENDENCIES" = "" ]; then CHANGED_FILES=$(git diff --name-only --diff-filter=ACMRTUXB "${TRAVIS_COMMIT_RANGE}") & if ! echo "${CHANGED_FILES}" | grep -qE "^(\\.php_cs(\\.dist)?|composer\\.lock)$"; then IFS=$'\n' EXTRA_ARGS=('--path-mode=intersection' '--' ${CHANGED_FILES[@]}); fi ; vendor/bin/php-cs-fixer fix --config=.php_cs.dist -v --dry-run --stop-on-violation --using-cache=no "${EXTRA_ARGS[@]}"
  - if [ "$TRAVIS_PHP_VERSION" = "7.1" ] && [ "DEPENDENCIES" = "" ]; then ./vendor/bin/phpstan analyse -l max -c phpstan.neon src tests --no-progress --no-interaction; fi
after_script:
  - if [ "$TRAVIS_PHP_VERSION" = "7.1" ] && [ "DEPENDENCIES" = "" ]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
