language: php
php:
  - 5.4
before_script:
    - wget http://getcomposer.org/composer.phar
    - php composer.phar install
    - 'wget http://pecl.php.net/get/APC-3.1.9.tgz ; tar -xzf APC-3.1.9.tgz ; sh -c "cd APC-3.1.9 && phpize && ./configure  && make && sudo make install" ; echo "extension=apc.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`'
script: phpunit --coverage-text
