language: php
sudo: false
php:
  - 7
  - 7.1
  - 7.2
cache:
  directories:
    - vendor
    - $HOME/.composer/cache
env:
  matrix:
    - DEPENDENCIES=""
    - DEPENDENCIES="--prefer-lowest --prefer-stable"
before_script:
  - composer self-update
  - composer update $DEPENDENCIES
  - if [[ $TRAVIS_PHP_VERSION = '7.1' ]] && [ "DEPENDENCIES" = "" ]; then COVERAGE="--coverage-clover=coverage.clover"; else phpenv config-rm xdebug.ini; fi
  - if [ "$TRAVIS_PHP_VERSION" = "7.1" ] && [ "DEPENDENCIES" = "" ]; then composer require --dev phpstan/phpstan-shim friendsofphp/php-cs-fixer; fi
script:
  - ./vendor/bin/phpunit $COVERAGE;
  - php demo/run.php
  - if [ "$TRAVIS_PHP_VERSION" = "7.1" ] && [ "DEPENDENCIES" = "" ]; then IFS=$'\n'; COMMIT_SCA_FILES=($(git diff --name-only --diff-filter=ACMRTUXB "${TRAVIS_COMMIT_RANGE}")); unset IFS; && ./vendor/bin/php-cs-fixer fix --config=.php_cs.php -v --dry-run --stop-on-violation --using-cache=no --path-mode=intersection -- "${COMMIT_SCA_FILES[@]}";fi
  - if [ "$TRAVIS_PHP_VERSION" = "7.1" ] && [ "DEPENDENCIES" = "" ]; then ./vendor/bin/phpstan analyse -l max -c phpstan.neon src tests --no-progress --no-interaction; fi
after_script:
  - if [ "$TRAVIS_PHP_VERSION" = "7.1" ] && [ "DEPENDENCIES" = "" ]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
